# Project: snake
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Food.o Snake1.o
LINKOBJ  = main.o Food.o Snake1.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -L"C:/Users/Mohamed/Downloads/SDL2_image-devel-2.6.2-mingw/SDL2_image-2.6.2/x86_64-w64-mingw32/lib" -L"C:/Users/Mohamed/Downloads/SDL2-devel-2.26.1-mingw/SDL2-2.26.1/x86_64-w64-mingw32/lib" -L"C:/Users/Mohamed/Downloads/SDL2_mixer-2.6.2/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/Mohamed/Downloads/SDL2-devel-2.26.1-mingw/SDL2-2.26.1/x86_64-w64-mingw32/include/SDL2" -I"C:/Users/Mohamed/Downloads/SDL2_image-devel-2.6.2-mingw/SDL2_image-2.6.2/x86_64-w64-mingw32/include/SDL2" -I"C:/Users/Mohamed/Downloads/SDL2_mixer-2.6.2/x86_64-w64-mingw32/include/SDL2"
BIN      = snake.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Food.o: Food.cpp
	$(CPP) -c Food.cpp -o Food.o $(CXXFLAGS)

Snake1.o: Snake1.cpp
	$(CPP) -c Snake1.cpp -o Snake1.o $(CXXFLAGS)
